const std = @import("std");
const testing = std.testing;

/// Epoll event masks
// https://github.com/torvalds/linux/blob/18a7e218cfcdca6666e1f7356533e4c988780b57/include/uapi/linux/eventpoll.h#L30
pub const Epoll = packed struct(u32) {
    // EPOLL event types (lower 16 bits)
    //
    /// The associated file is available for read(2) operations
    in: bool = false,
    /// There is an exceptional condition on the file descriptor
    pri: bool = false,
    /// The associated file is available for write(2) operations
    out: bool = false,
    /// Error condition happened on the associated file descriptor
    err: bool = false,
    /// Hang up happened on the associated file descriptor
    hup: bool = false,
    /// Invalid request: fd not open
    nval: bool = false,
    /// Normal data may be read
    rdnorm: bool = false,
    /// Priority data may be read
    rdband: bool = false,
    // COMMIT: new flags
    /// Writing is now possible (normal data)
    wrnorm: bool = false,
    /// Priority data may be written
    wrband: bool = false,
    /// Message available (unused on Linux)
    msg: bool = false,
    _12: u2 = 0,
    /// Stream socket peer closed connection
    rdhup: bool = false,
    _15: u13 = 0,
    // EPOLL input flags (Higher order flags are included as internal stat)
    //
    /// Internal flag - wakeup generated by io_uring, used to detect
    /// recursion back into the io_uring poll handler
    uring_wake: bool = false,
    /// Set exclusive wakeup mode for the target file descriptor
    exclusive: bool = false,
    /// Request the handling of system wakeup events so as to prevent system
    /// suspends from happening while those events are being processed.
    /// Assuming neither EPOLLET nor EPOLLONESHOT is set, system suspends will
    /// not be re-allowed until epoll_wait is called again after consuming the
    /// wakeup event(s).
    /// Requires CAP_BLOCK_SUSPEND
    wakeup: bool = false,
    /// Set the One Shot behaviour for the target file descriptor
    oneshot: bool = false,
    /// Set the Edge Triggered behaviour for the target file descriptor
    et: bool = false,

    // Deprecated Named constants
    // EPOLL event types
    pub const IN: u32 = @bitCast(Epoll{ .in = true });
    pub const PRI: u32 = @bitCast(Epoll{ .pri = true });
    pub const OUT: u32 = @bitCast(Epoll{ .out = true });
    pub const ERR: u32 = @bitCast(Epoll{ .err = true });
    pub const HUP: u32 = @bitCast(Epoll{ .hup = true });
    pub const NVAL: u32 = @bitCast(Epoll{ .nval = true });
    pub const RDNORM: u32 = @bitCast(Epoll{ .rdnorm = true });
    pub const RDBAND: u32 = @bitCast(Epoll{ .rdband = true });
    pub const WRNORM: u32 = @bitCast(Epoll{ .wrnorm = true });
    pub const WRBAND: u32 = @bitCast(Epoll{ .wrband = true });
    pub const MSG: u32 = @bitCast(Epoll{ .msg = true });
    pub const RDHUP: u32 = @bitCast(Epoll{ .rdhup = true });

    // EPOLL input flags
    pub const URING_WAKE: u32 = @bitCast(Epoll{ .uring_wake = true });
    pub const EXCLUSIVE: u32 = @bitCast(Epoll{ .exclusive = true });
    pub const WAKEUP: u32 = @bitCast(Epoll{ .wakeup = true });
    pub const ONESHOT: u32 = @bitCast(Epoll{ .oneshot = true });
    pub const ET: u32 = @bitCast(Epoll{ .et = true });
};

pub const EPOLL = struct {
    pub const IN: u32 = 0x00000001;
    pub const PRI: u32 = 0x00000002;
    pub const OUT: u32 = 0x00000004;
    pub const ERR: u32 = 0x00000008;
    pub const HUP: u32 = 0x00000010;
    pub const NVAL: u32 = 0x00000020;
    pub const RDNORM: u32 = 0x00000040;
    pub const RDBAND: u32 = 0x00000080;
    pub const WRNORM: u32 = 0x00000100;
    pub const WRBAND: u32 = 0x00000200;
    pub const MSG: u32 = 0x00000400;
    pub const RDHUP: u32 = 0x00002000;

    pub const URING_WAKE: u32 = 1 << 27;
    pub const EXCLUSIVE: u32 = 1 << 28;
    pub const WAKEUP: u32 = 1 << 29;
    pub const ONESHOT: u32 = 1 << 30;
    pub const ET: u32 = 1 << 31;
};

test "Poll - constants match EPOLL constants" {
    try testing.expectEqual(EPOLL.IN, Epoll.IN);
    try testing.expectEqual(EPOLL.PRI, Epoll.PRI);
    try testing.expectEqual(EPOLL.OUT, Epoll.OUT);
    try testing.expectEqual(EPOLL.ERR, Epoll.ERR);
    try testing.expectEqual(EPOLL.HUP, Epoll.HUP);
    try testing.expectEqual(EPOLL.NVAL, Epoll.NVAL);
    try testing.expectEqual(EPOLL.RDNORM, Epoll.RDNORM);
    try testing.expectEqual(EPOLL.RDBAND, Epoll.RDBAND);
    try testing.expectEqual(EPOLL.WRNORM, Epoll.WRNORM);
    try testing.expectEqual(EPOLL.WRBAND, Epoll.WRBAND);
    try testing.expectEqual(EPOLL.MSG, Epoll.MSG);
    try testing.expectEqual(EPOLL.RDHUP, Epoll.RDHUP);

    try testing.expectEqual(EPOLL.URING_WAKE, Epoll.URING_WAKE);
    try testing.expectEqual(EPOLL.EXCLUSIVE, Epoll.EXCLUSIVE);
    try testing.expectEqual(EPOLL.WAKEUP, Epoll.WAKEUP);
    try testing.expectEqual(EPOLL.ONESHOT, Epoll.ONESHOT);
    try testing.expectEqual(EPOLL.ET, Epoll.ET);
}

test "Poll - combine multiple events" {
    const events = Epoll{
        .in = true,
        .out = true,
        .err = true,
    };
    const expected = Epoll.IN | Epoll.OUT | Epoll.ERR;
    try testing.expectEqual(expected, @as(u32, @bitCast(events)));
}

test "Poll - convert from u32" {
    const value: u32 = Epoll.IN | Epoll.OUT | Epoll.RDHUP;
    const events: Epoll = @bitCast(value);

    try testing.expect(events.in);
    try testing.expect(events.out);
    try testing.expect(events.rdhup);
    try testing.expect(!events.err);
    try testing.expect(!events.hup);
}

test "Poll - default is all false" {
    const events = Epoll{};
    try testing.expectEqual(@as(u32, 0), @as(u32, @bitCast(events)));
}

test "Poll - size check" {
    try testing.expectEqual(@sizeOf(u32), @sizeOf(Epoll));
}

test "Poll - round trip conversion" {
    const original = Epoll{
        .in = true,
        .out = true,
        .hup = true,
        .rdhup = true,
    };
    const value: u32 = @bitCast(original);
    const restored: Epoll = @bitCast(value);
    try testing.expectEqual(original, restored);
}

test "Poll - common read events" {
    const events = Epoll{
        .in = true,
        .rdnorm = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.IN | Epoll.RDNORM;
    try testing.expectEqual(expected, value);
}

test "Poll - common write events" {
    const events = Epoll{
        .out = true,
        .wrnorm = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.OUT | Epoll.WRNORM;
    try testing.expectEqual(expected, value);
}

test "Poll - error and hangup events" {
    const events = Epoll{
        .err = true,
        .hup = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.ERR | Epoll.HUP;
    try testing.expectEqual(expected, value);
}

test "Poll - priority data events" {
    const events = Epoll{
        .pri = true,
        .rdband = true,
        .wrband = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.PRI | Epoll.RDBAND | Epoll.WRBAND;
    try testing.expectEqual(expected, value);
}

test "Poll - rdhup for connection closure" {
    const events = Epoll{
        .in = true,
        .rdhup = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.IN | Epoll.RDHUP;
    try testing.expectEqual(expected, value);
}

test "Poll - typical server read events" {
    // Common pattern: wait for readable with error detection
    const events = Epoll{
        .in = true,
        .err = true,
        .hup = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.IN | Epoll.ERR | Epoll.HUP;
    try testing.expectEqual(expected, value);
}

test "Poll - typical server write events" {
    // Common pattern: wait for writable with error detection
    const events = Epoll{
        .out = true,
        .err = true,
        .hup = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.OUT | Epoll.ERR | Epoll.HUP;
    try testing.expectEqual(expected, value);
}

test "Poll - bidirectional events" {
    const events = Epoll{
        .in = true,
        .out = true,
        .err = true,
        .hup = true,
        .rdhup = true,
    };
    const value: u32 = @bitCast(events);
    const expected = Epoll.IN | Epoll.OUT | Epoll.ERR | Epoll.HUP | Epoll.RDHUP;
    try testing.expectEqual(expected, value);
}

test "Poll - check individual event flags" {
    const value: u32 = Epoll.IN | Epoll.ERR;
    const events: Epoll = @bitCast(value);

    // Check which events occurred
    if (events.err) {
        // Handle error
        try testing.expect(true);
    }
    if (events.in) {
        // Handle readable
        try testing.expect(true);
    }
    if (events.out) {
        // This shouldn't happen
        try testing.expect(false);
    }
}

test "Poll - all events set" {
    const events = Epoll{
        .in = true,
        .pri = true,
        .out = true,
        .err = true,
        .hup = true,
        .nval = true,
        .rdnorm = true,
        .rdband = true,
        .wrnorm = true,
        .wrband = true,
        .msg = true,
        .rdhup = true,
    };
    const expected = Epoll.IN | Epoll.PRI | Epoll.OUT | Epoll.ERR | Epoll.HUP |
        Epoll.NVAL | Epoll.RDNORM | Epoll.RDBAND | Epoll.WRNORM |
        Epoll.WRBAND | Epoll.MSG | Epoll.RDHUP;
    try testing.expectEqual(expected, @as(u32, @bitCast(events)));
}
